### ISSUE TITLE
Please add the solution files as release

### ISSUE THREAD

**Issue by rajyraman** [Akouddane/EasyPlugins#1]
I cannot add this tool to my XrmToolBox solution feed, as it does not have any releases. My tool helps users install GitHub solutions -> https://github.com/rajyraman/Solution-Installer-for-XrmToolBox

**Comment by Akouddane** [comment]
Done! Thanks
Amine

**Comment by rajyraman** [comment]
That was fast. 👍

**Comment by rajyraman** [comment]
Added to tool.

![image](https://user-images.githubusercontent.com/5035266/39625785-66616f66-4fe2-11e8-9247-0844abdea5fb.png)

**Comment by rajyraman** [comment]
Added to my tool.

![image](https://user-images.githubusercontent.com/5035266/39625813-97b5aed8-4fe2-11e8-80b5-e520c1c2ba67.png)
