### ISSUE TITLE
Get an error when testing samples

### ISSUE THREAD

**Issue by ashende** [Akouddane/EasyPlugins#3]
I have attached the error messages.

Error testing sample 1.

[ErrorDetails (1).txt](https://github.com/Akouddane/EasyPlugins/files/1977235/ErrorDetails.1.txt)

Error testing sample 5.

[ErrorDetails (4).txt](https://github.com/Akouddane/EasyPlugins/files/1977805/ErrorDetails.4.txt)

Thanks.

**Comment by Akouddane** [comment]
Hi ashende,

Thank you for using EasyPlugins.
What version of Dynamics CRM you are using ?
Please post your configuration here so I can check is everything is OK. You can export your configuration in the main menu.
I just tried samples 1 & 5 by importing them from documentation on version 9.0.2.54 and it works fine.

Thanks
Amine

**Comment by ashende** [comment]
Amine, 
I am also using the same version (9.0.2.54).
I have attached both samples here.
[Sample1.txt](https://github.com/Akouddane/EasyPlugins/files/1978000/Sample1.txt)
[Sample5.txt](https://github.com/Akouddane/EasyPlugins/files/1978001/Sample5.txt)
Thanks.

**Comment by Akouddane** [comment]
Ok Thanks
Sample 1: 
replace "#id" by "#Id" on parentcustomerid definition
Sample 5: 
Same probleme here, replace "#id" by "Id" on annotationId definition, annotationid is not necessary here, override action is not an update, it will "replace" the current attributes on the initial creation/update.

Question : 
How could you save with an invalid expression ? Normally, Save button is disabled until you click on "Test Expression".
When I test "#id" I have "Line 1: Unexpected token ILLEGAL" error, and I can't save.

Thanks

**Comment by ashende** [comment]
That resolved both issues. Thanks.
Not sure how I was able to save an invalid expression. I tried to save it again and now I am not able to.
Thanks for the quick response and keep up the good work!
