### ISSUE TITLE
Multiple lines text fields not available in the attributes list?

### ISSUE THREAD

**Issue by ashende** [Akouddane/EasyPlugins#4]
It appears that multiple lines text fields are not available in the attributes list. For example, 'description' fields in account and contact entities do not appear in the attributes list for selection for trigger or update. Thanks.

**Comment by Akouddane** [comment]
Hi there,

My bad, Memo type was not managed in attributes retrieve.
Please update your EasyPlugins to the new release 2.0.0.1
[https://github.com/Akouddane/EasyPlugins/releases/tag/2.0.0.1](url)

Thanks for your feedback
Amine

**Comment by ashende** [comment]
Resolved. Thanks!
