### ISSUE TITLE
Is it possible to get reference to record created by action?

### ISSUE THREAD

**Issue by ashende** [Akouddane/EasyPlugins#5]
Is it possible to get a reference to the record created by the "create" action and use it in subsequent action(s)?
For example, how do I implement the following requirement?

On creation of Account:
1. Create a Contact
2. Create a Note for the Contact created above

Thanks.

**Comment by Akouddane** [comment]
Great idea :)
I'll try to add this feature on the next release by generating a new type of parameter.

For now, you can implement your requirement like the following : 
- put in an unused text field in your contact = "auto generated"
- add a plugin on contacts post creation with condition : field == "auto generated" and create a note for it with a max depth execution = 2.

Thanks

**Comment by ashende** [comment]
Yes. However, will both plugins be executed synchronously? Thanks.

**Comment by Akouddane** [comment]
Yes, it can be executed synchronously.

**Comment by Akouddane** [comment]
Hi ashende,

Good news :)
A new version (2.0.0.2) is released on dist directory with some new features :
- "Create Action" adds a new parameter type "Created Id(s)"
- DCRM actions can be called and if output is defined, a new parameter is added that contains an array of output values.

Thanks for your suggestions.

Amine

**Comment by ashende** [comment]
Thank you! Will try this out soon.
